[package]
name = "odbc_client"
version = "0.1.0"
authors = ["Patrick Meredith <pmeredit@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
odbc = "0.17.0"
env_logger = "0.7.1"
clap = "3.0.0-beta.1"
